I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 20, in script
    f '''
TypeError: Unexpected keyword arguments: 'side_image'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script
    f '''
  File "E:\programm\renpy-8.0.3-sdk\renpy\ast.py", line 923, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "E:\programm\renpy-8.0.3-sdk\renpy\exports.py", line 1462, in say
    who(what, *args, **kwargs)
  File "E:\programm\renpy-8.0.3-sdk\renpy\character.py", line 1319, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "E:\programm\renpy-8.0.3-sdk\renpy\character.py", line 975, in do_display
    display_say(who,
  File "E:\programm\renpy-8.0.3-sdk\renpy\character.py", line 613, in display_say
    what_text = renpy.display.screen.get_widget(what_text[0], what_text[1], what_text[2])
  File "E:\programm\renpy-8.0.3-sdk\renpy\display\screen.py", line 1392, in get_displayable
    screen.update()
  File "E:\programm\renpy-8.0.3-sdk\renpy\display\screen.py", line 653, in update
    self.screen.function(**self.scope)
  File "E:\programm\renpy-8.0.3-sdk\renpy\ast.py", line 296, in apply_arguments
    return parameters.apply(args, kwargs, ignore_errors)
  File "E:\programm\renpy-8.0.3-sdk\renpy\ast.py", line 281, in apply
    raise TypeError(
TypeError: Unexpected keyword arguments: 'side_image'

Windows-10-10.0.19042 AMD64
Ren'Py 8.1.0.23020701n
Найди Фумо 1.0
Tue Mar 28 23:07:17 2023
